language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install: 
  - "pip install pygtk --use-mirrors"
  - "pip install numpy --use-mirrors"
  - "pip install scipy --use-mirrors"
