#!/bin/bash
# install plotting scripts
# if you do not have root privaliges run insall [directory]
# with a directory in the system path


DIR=$( pwd )
INSTALL=${1:-/usr/bin}

if [ $INSTALL = /usr/bin ]
  then sudo rm $INSTALL/plot_SQUID_data
    sudo rm $INSTALL/plot_4circle_data
    sudo rm $INSTALL/plot_reflectometer_data
    sudo rm $INSTALL/psd
    sudo rm $INSTALL/p4d
    sudo rm $INSTALL/prd
    sudo rm $INSTALL/pin12
    sudo rm $INSTALL/dnsplot
    sudo rm $INSTALL/treffplot
    sudo rm $INSTALL/plot.py
  else rm $INSTALL/plot_SQUID_data
    rm $INSTALL/plot_4circle_data
    rm $INSTALL/plot_reflectometer_data
    rm $INSTALL/psd
    rm $INSTALL/p4d
    rm $INSTALL/prd
    rm $INSTALL/pin12
    rm $INSTALL/dnsplot
    rm $INSTALL/treffplot
    rm $INSTALL/plot.py
fi
