#!/usr/bin/env python
'''
 Add-on for plot_SQUID_data.py to help calculating the SQUID calibration factors
'''

__author__ = "Artur Glavic"
__copyright__ = "Copyright 2008-2009"
__credits__ = []
__license__ = "None"
__version__ = "0.6"
__maintainer__ = "Artur Glavic"
__email__ = "a.glavic@fz-juelich.de"
__status__ = "Prototype"

# Suszeptability of Paladium at Roomtemperature:
Chi_Pd=5.25e-6 #[emu/gauss/g]
# Mass of the used Paladium calibration Sample
m_Pd=0.26867 #[g]

